name: real_estate_mock
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  iconsax_flutter: ^1.0.0
  google_fonts: ^6.2.1
  gap: ^3.0.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  build_runner:
  flutter_gen_runner:


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.jpg"
  adaptive_icon_background: "#FC9E12"
  adaptive_icon_foreground: "assets/images/icon.jpg"

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/

